env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - prettier
rules:
  react/react-in-jsx-scope: off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoid-escape
  semi:
    - error
    - always
  no-console:
    - error
    - allow: ['error']
  max-len:
    - warn
    - code: 120
      ignoreComments: true
      ignoreTrailingComments: true
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
  quote-props:
    - error
    - consistent
  brace-style:
    - error
    - 1tbs
  max-statements-per-line:
    - error
    - max: 1
  jsx-quotes:
    - error
    - prefer-single
  prettier/prettier:
    [
      'warn',
      {
        linebreakStyle: 'unix',
        trailingComma: 'es5',
        tabWidth: 2,
        semi: true,
        singleQuote: true,
        useTabs: true,
        noconsole: true,
        printWidth: 100,
        bracketSpacing: true,
        quoteProps: consistent,
        bracketSameLine: false,
        singleAttributePerLine: true,
        jsxSingleQuote: true,
      },
    ]
